---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployement
  labels:
    app: jenkins
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jenkinsapp
  strategy:
      type: RollingUpdate 
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
  template:
    metadata:
      name: Jenkins-pod
      labels:
        app: jenkinsapp
        version: "2.60"
        env: production
    spec:
      containers:
        - name: jenkins-cont
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080
              protocol: TCP


    
