---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: httpd-rs
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
     name: http-pod
     labels:
       env: dev
    spec:
      containers:
        - image: httpd
          name:  httpd-container
          ports:
          - name: http-port
            containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
            

