---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo1
  labels:
    environment: dev
    team: infra-ops
    project: qt-ecomm
spec:
  containers:
    - name: container-with-limits
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP