---
apiVersion: v1
kind: Pod
metadata:
  name: res-req-demo
spec:
  containers:
    - name: container-with-limits
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: "31"
          memory: "1024M"
        requests:
          cpu: "16"
          memory: "512M"